version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_mailservice
    ports:
      - "6500:5432"
    volumes:
      - mailservice_1:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app_network

  mail_service_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mailservice_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      # Use the service name 'postgres' instead of localhost
      DATABASE_URL: postgresql://postgres:Kanak%40posts@localhost:5432/mail_service

    env_file:
      - ./.env
    volumes:
      - .backend/api/src:/app/src:ro
    networks:
      - app_network

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    container_name: mailservice_frontend
    depends_on:
      - postgres
      - mail_service_api
    
    networks:
      - app_network

    ports:
      - "8021:8021"

volumes:
  mailservice_1:

networks:
  app_network:
    driver: bridge
