services:
  postgres:
    image: postgres:latest
    container_name: postgres_mailservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mail_service
    ports:
      - "6500:5432"
    volumes:
      - mailservice_1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mail_service"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./.env
    networks:
      - app_network

  mail_service_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailservice_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Use the service name 'postgres' instead of localhost
      DATABASE_URL: postgresql://postgres:postgres@postgres_mailservice:5432/mail_service

    env_file:
      - ./.env
    networks:
      - app_network

volumes:
  mailservice_1:

networks:
  app_network:
    driver: bridge
