name: Run Backend Tests

on:
  push:
    branches: [develop, main]

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: 1.97.0

      - name: Show Rust version
        run: |
          rustc --version
          cargo --version

      - name: Install dependencies
        run: cargo build
        working-directory: backend

      - name: Run tests
        run: cargo test
        working-directory: backend
