name: Run backend tests

on:
    push:
        branches: [develop, main, 32-feat/test-CI]
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop

jobs:
    test: 
        name: Run backend tests
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: moonrepo/setup-rust@v1
              with:
                channel: 1.83.0
            
            # Add this step to check if Cargo.toml is present in the directory
            - name: List directory contents
              run: ls -la  # This will show the directory contents

            - name: Navigate to the backend directory (if applicable)
              run: cd backend  # If your Cargo.toml is in a subdirectory, change this path
                      
            - name: Verify Cargo.toml is present
              run: ls -la  # This will confirm if Cargo.toml is in the directory you're running cargo from

            - name: Install dependencies
              run: cargo build

            - name: Run tests
              run: cargo test

        