name: Run Backend Tests

on:
    push:
        branches: [develop, main, 32-feat/test-CI]
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop

jobs:
    test: 
        name: Run Backend Tests
        runs-on: ubuntu-latest

        permissions:
          actions: read
          contents: read
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: moonrepo/setup-rust@v1
              with:
                channel: 1.83.0   # rustc version
            
            - name: Install dependencies
              run: cargo build
              working-directory: backend

            - name: Run tests
              run: cargo test
              working-directory: backend

        